/* 由 省份数据.xlsx 自动生成；请勿手工修改。 */
window.PMKT_PROVINCE_DATA = {
  "schemaVersion": 1,
  "dataVersion": "2026-07-10",
  "source": "省份数据.xlsx",
  "sourceUpdatedAt": "2026-07-10T00:45:03.435Z",
  "sheetNames": [
    "数据收集",
    "省份数据"
  ],
  "provinceCount": 31,
  "globalQualityNotes": [
    "省份数据表 C1 仍为占位表头“XXXX合约率”，正式发布前需确认指标名称",
    "10年以上网龄客户离网规模同比未声明单位，当前保留源值",
    "平台供应商存在 OB/OBS、简称与疑似错别字（如山西“斯特奇”），未自动归一",
    "波次及路径仅有 1/2/3 原值且缺代码表，系统仅展示波次，不推导完成率"
  ],
  "qualityIssueCount": 11,
  "provinces": [
    {
      "name": "河南",
      "sourceRow": 3,
      "top1Intent": true,
      "dataAccess": "1、OBS数据融合\n2、O域数据：DPI/NWDAF、SA/资管/装维、网络投诉",
      "dataGovernance": "公司级数据治理",
      "modelCapability": "120+小模型，准确率30%",
      "challenge": "离网/降档/升档/营销触达工单调度",
      "networkExperienceRights": "高铁包，演唱会包，效果一般",
      "wave": 1,
      "platform": {
        "bigData": "华为",
        "iop": "华为",
        "crm": "亚信",
        "boss": "亚信",
        "seq": "中兴",
        "nwdaf": "华为",
        "ado": "华为"
      },
      "landscape": "强格局",
      "kpi": {
        "globalRetention": "103.0%",
        "contractRate": "80.7%",
        "otherNetMainCardRate": "4.2%",
        "threePlanPenetration": "8.8%",
        "cumulativeMonthlyChurn": "0.96%",
        "premium3dMonthlyChurn": "0.59%",
        "stockMonthlyChurn": "3.01%",
        "incrementalMonthlyChurn": "2.41%",
        "tenYearChurnScaleYoY": -21.5
      },
      "kpiValuePct": {
        "globalRetention": 1.03,
        "contractRate": 0.807,
        "otherNetMainCardRate": 0.042,
        "threePlanPenetration": 0.08800000000000001,
        "cumulativeMonthlyChurn": 0.0096,
        "premium3dMonthlyChurn": 0.0059,
        "stockMonthlyChurn": 0.0301,
        "incrementalMonthlyChurn": 0.0241
      },
      "qualityFlags": [
        "拍照全球通保有率待复核：103.0%"
      ]
    },
    {
      "name": "黑龙江",
      "sourceRow": 4,
      "top1Intent": true,
      "dataAccess": "1、OB数据融合\n2、O域数据：DPI/位置",
      "dataGovernance": null,
      "modelCapability": "小模型为主",
      "challenge": "价值流量经营",
      "networkExperienceRights": null,
      "wave": null,
      "platform": {
        "bigData": "华为",
        "iop": "亚信",
        "crm": "思特奇",
        "boss": "思特奇",
        "seq": "中兴",
        "nwdaf": "中兴",
        "ado": "国信+亚信"
      },
      "landscape": "部分格局",
      "kpi": {
        "globalRetention": "99.1%",
        "contractRate": "83.3%",
        "otherNetMainCardRate": "5.1%",
        "threePlanPenetration": "12.4%",
        "cumulativeMonthlyChurn": "1.07%",
        "premium3dMonthlyChurn": "0.64%",
        "stockMonthlyChurn": "3.71%",
        "incrementalMonthlyChurn": "5.51%",
        "tenYearChurnScaleYoY": -22.2
      },
      "kpiValuePct": {
        "globalRetention": 0.991,
        "contractRate": 0.833,
        "otherNetMainCardRate": 0.051,
        "threePlanPenetration": 0.124,
        "cumulativeMonthlyChurn": 0.010700000000000001,
        "premium3dMonthlyChurn": 0.0064,
        "stockMonthlyChurn": 0.0371,
        "incrementalMonthlyChurn": 0.055099999999999996
      },
      "qualityFlags": []
    },
    {
      "name": "甘肃",
      "sourceRow": 5,
      "top1Intent": true,
      "dataAccess": "1、OB数据融合\n2、O域数据：DPI/位置",
      "dataGovernance": null,
      "modelCapability": "小模型为主",
      "challenge": "价值流量经营",
      "networkExperienceRights": "地铁包10块，春节（交通枢纽加速包），马拉松畅享包，销售不理想平均一万个左右",
      "wave": null,
      "platform": {
        "bigData": "华为",
        "iop": "亚信",
        "crm": "亚信",
        "boss": "亚信",
        "seq": "东方通",
        "nwdaf": "中兴",
        "ado": "微品+华为"
      },
      "landscape": "部分格局",
      "kpi": {
        "globalRetention": "98.0%",
        "contractRate": "91.1%",
        "otherNetMainCardRate": "7.2%",
        "threePlanPenetration": "8.3%",
        "cumulativeMonthlyChurn": "1.17%",
        "premium3dMonthlyChurn": "0.61%",
        "stockMonthlyChurn": "3.67%",
        "incrementalMonthlyChurn": "2.37%",
        "tenYearChurnScaleYoY": 0.9
      },
      "kpiValuePct": {
        "globalRetention": 0.98,
        "contractRate": 0.9109999999999999,
        "otherNetMainCardRate": 0.07200000000000001,
        "threePlanPenetration": 0.083,
        "cumulativeMonthlyChurn": 0.011699999999999999,
        "premium3dMonthlyChurn": 0.0060999999999999995,
        "stockMonthlyChurn": 0.036699999999999997,
        "incrementalMonthlyChurn": 0.023700000000000002
      },
      "qualityFlags": []
    },
    {
      "name": "贵州",
      "sourceRow": 6,
      "top1Intent": true,
      "dataAccess": "1、OB数据融合\n2、O域数据：DPI/位置、SA",
      "dataGovernance": null,
      "modelCapability": "小模型为主",
      "challenge": "离网压降，高铁场景体验经营",
      "networkExperienceRights": null,
      "wave": null,
      "platform": {
        "bigData": "华为",
        "iop": "亚信",
        "crm": "亚信",
        "boss": "亚信",
        "seq": "中兴",
        "nwdaf": "华为",
        "ado": "华为+亚信"
      },
      "landscape": "部分格局",
      "kpi": {
        "globalRetention": "98.4%",
        "contractRate": "60.0%",
        "otherNetMainCardRate": "6.4%",
        "threePlanPenetration": "8.0%",
        "cumulativeMonthlyChurn": "1.15%",
        "premium3dMonthlyChurn": "0.78%",
        "stockMonthlyChurn": "3.31%",
        "incrementalMonthlyChurn": "3.16%",
        "tenYearChurnScaleYoY": 42
      },
      "kpiValuePct": {
        "globalRetention": 0.9840000000000001,
        "contractRate": 0.6,
        "otherNetMainCardRate": 0.064,
        "threePlanPenetration": 0.08,
        "cumulativeMonthlyChurn": 0.0115,
        "premium3dMonthlyChurn": 0.0078000000000000005,
        "stockMonthlyChurn": 0.0331,
        "incrementalMonthlyChurn": 0.0316
      },
      "qualityFlags": []
    },
    {
      "name": "广西",
      "sourceRow": 7,
      "top1Intent": true,
      "dataAccess": "1、OBS数据融合\n2、O域数据：DPI/NWDAF/位置",
      "dataGovernance": "OBS数据治理",
      "modelCapability": "小模型为主",
      "challenge": "OBS数据集成打通支撑用户画像分群；面向高铁、景区、重点口碑场景的5G-A体验经营",
      "networkExperienceRights": null,
      "wave": 2,
      "platform": {
        "bigData": "华为",
        "iop": "华为",
        "crm": "亚信",
        "boss": "亚信",
        "seq": "华为",
        "nwdaf": "华为",
        "ado": "华为+亚信"
      },
      "landscape": "强格局",
      "kpi": {
        "globalRetention": "100.2%",
        "contractRate": "69.6%",
        "otherNetMainCardRate": "6.5%",
        "threePlanPenetration": "6.9%",
        "cumulativeMonthlyChurn": "1.45%",
        "premium3dMonthlyChurn": "0.88%",
        "stockMonthlyChurn": "2.62%",
        "incrementalMonthlyChurn": "3.45%",
        "tenYearChurnScaleYoY": 7.4
      },
      "kpiValuePct": {
        "globalRetention": 1.002,
        "contractRate": 0.696,
        "otherNetMainCardRate": 0.065,
        "threePlanPenetration": 0.069,
        "cumulativeMonthlyChurn": 0.014499999999999999,
        "premium3dMonthlyChurn": 0.0088,
        "stockMonthlyChurn": 0.0262,
        "incrementalMonthlyChurn": 0.0345
      },
      "qualityFlags": [
        "拍照全球通保有率待复核：100.2%"
      ]
    },
    {
      "name": "四川",
      "sourceRow": 8,
      "top1Intent": true,
      "dataAccess": "1、OB数据融合\n2、O域数据：DPI/NWDAF、SA",
      "dataGovernance": "OB数据治理",
      "modelCapability": "小模型，准确率8%",
      "challenge": "基于大数据平台的用户画像和精准客群细分",
      "networkExperienceRights": "基于智能板做过场馆加速包，成效一般",
      "wave": 2,
      "platform": {
        "bigData": "华为",
        "iop": "亚信",
        "crm": "思特奇",
        "boss": "思特奇",
        "seq": "华为",
        "nwdaf": "华为",
        "ado": "亚信"
      },
      "landscape": "部分格局",
      "kpi": {
        "globalRetention": "99.1%",
        "contractRate": "81.7%",
        "otherNetMainCardRate": "5.2%",
        "threePlanPenetration": "9.3%",
        "cumulativeMonthlyChurn": "1.08%",
        "premium3dMonthlyChurn": "0.75%",
        "stockMonthlyChurn": "2.96%",
        "incrementalMonthlyChurn": "1.63%",
        "tenYearChurnScaleYoY": 33.3
      },
      "kpiValuePct": {
        "globalRetention": 0.991,
        "contractRate": 0.8170000000000001,
        "otherNetMainCardRate": 0.052000000000000005,
        "threePlanPenetration": 0.09300000000000001,
        "cumulativeMonthlyChurn": 0.0108,
        "premium3dMonthlyChurn": 0.0075,
        "stockMonthlyChurn": 0.0296,
        "incrementalMonthlyChurn": 0.0163
      },
      "qualityFlags": []
    },
    {
      "name": "河北",
      "sourceRow": 9,
      "top1Intent": false,
      "dataAccess": "1、OB数据融合\n2、O域数据：DPI、位置、SA单板数据",
      "dataGovernance": null,
      "modelCapability": "小模型为主",
      "challenge": null,
      "networkExperienceRights": "场馆包，游戏加速包，校园包，5G-A套餐用户默认享有差异化套餐，普惠包（河北移动全网客户享有扫码付款场景的差异化保障权益）",
      "wave": 2,
      "platform": {
        "bigData": "华为",
        "iop": "华为",
        "crm": "华为",
        "boss": "华为",
        "seq": "华为",
        "nwdaf": "华为",
        "ado": "华为"
      },
      "landscape": "强格局",
      "kpi": {
        "globalRetention": "97.2%",
        "contractRate": "76.4%",
        "otherNetMainCardRate": "7.5%",
        "threePlanPenetration": "9.8%",
        "cumulativeMonthlyChurn": "0.77%",
        "premium3dMonthlyChurn": "0.59%",
        "stockMonthlyChurn": "2.51%",
        "incrementalMonthlyChurn": "3.39%",
        "tenYearChurnScaleYoY": -12.4
      },
      "kpiValuePct": {
        "globalRetention": 0.972,
        "contractRate": 0.764,
        "otherNetMainCardRate": 0.075,
        "threePlanPenetration": 0.098,
        "cumulativeMonthlyChurn": 0.0077,
        "premium3dMonthlyChurn": 0.0059,
        "stockMonthlyChurn": 0.025099999999999997,
        "incrementalMonthlyChurn": 0.0339
      },
      "qualityFlags": []
    },
    {
      "name": "天津",
      "sourceRow": 10,
      "top1Intent": false,
      "dataAccess": "1、市场部运营取自B域数据，O域数据应用占比非常低（出于安全管理因素）",
      "dataGovernance": "OBS数据治理",
      "modelCapability": "小模型为主",
      "challenge": null,
      "networkExperienceRights": null,
      "wave": 2,
      "platform": {
        "bigData": "华为",
        "iop": "华为",
        "crm": "亚信",
        "boss": "亚信",
        "seq": "华为",
        "nwdaf": "华为",
        "ado": "华为"
      },
      "landscape": "强格局",
      "kpi": {
        "globalRetention": "90.4%",
        "contractRate": "82.0%",
        "otherNetMainCardRate": "7.7%",
        "threePlanPenetration": "12.0%",
        "cumulativeMonthlyChurn": "0.86%",
        "premium3dMonthlyChurn": "0.61%",
        "stockMonthlyChurn": "2.73%",
        "incrementalMonthlyChurn": "5.32%",
        "tenYearChurnScaleYoY": -36.4
      },
      "kpiValuePct": {
        "globalRetention": 0.904,
        "contractRate": 0.82,
        "otherNetMainCardRate": 0.077,
        "threePlanPenetration": 0.12,
        "cumulativeMonthlyChurn": 0.0086,
        "premium3dMonthlyChurn": 0.0060999999999999995,
        "stockMonthlyChurn": 0.0273,
        "incrementalMonthlyChurn": 0.053200000000000004
      },
      "qualityFlags": []
    },
    {
      "name": "湖南",
      "sourceRow": 11,
      "top1Intent": false,
      "dataAccess": "1、OB数据融合\n2、O域数据：DPI、物联网、资管、故障",
      "dataGovernance": null,
      "modelCapability": "小模型为主",
      "challenge": null,
      "networkExperienceRights": null,
      "wave": null,
      "platform": {
        "bigData": "华为",
        "iop": "华为",
        "crm": "亚信",
        "boss": "亚信",
        "seq": "中兴",
        "nwdaf": "华为",
        "ado": "华为"
      },
      "landscape": "强格局",
      "kpi": {
        "globalRetention": "100.0%",
        "contractRate": "80.0%",
        "otherNetMainCardRate": "6.6%",
        "threePlanPenetration": "8.1%",
        "cumulativeMonthlyChurn": "1.57%",
        "premium3dMonthlyChurn": "0.72%",
        "stockMonthlyChurn": "7.51%",
        "incrementalMonthlyChurn": "4.84%",
        "tenYearChurnScaleYoY": 3.4
      },
      "kpiValuePct": {
        "globalRetention": 1,
        "contractRate": 0.8,
        "otherNetMainCardRate": 0.066,
        "threePlanPenetration": 0.081,
        "cumulativeMonthlyChurn": 0.015700000000000002,
        "premium3dMonthlyChurn": 0.0072,
        "stockMonthlyChurn": 0.0751,
        "incrementalMonthlyChurn": 0.0484
      },
      "qualityFlags": []
    },
    {
      "name": "重庆",
      "sourceRow": 12,
      "top1Intent": true,
      "dataAccess": "1、100+ OBS数据融合，缺乏多维关联，数据质量缺少评估机制\n2、O域数据：SEQ",
      "dataGovernance": "无数据治理",
      "modelCapability": "小模型，提前1个月预测，准确率20%（客户希望提前3个月预测）",
      "challenge": "弃卡，一降到底，营销重复派单",
      "networkExperienceRights": "高端用户已默开5G-A，但基本没做体验经营，只作为流量激发手段",
      "wave": 3,
      "platform": {
        "bigData": "亚信",
        "iop": "亚信",
        "crm": "华为",
        "boss": "华为",
        "seq": "华为",
        "nwdaf": "中兴",
        "ado": "华为"
      },
      "landscape": "友商格局",
      "kpi": {
        "globalRetention": "98.7%",
        "contractRate": "86.2%",
        "otherNetMainCardRate": "5.9%",
        "threePlanPenetration": "11.5%",
        "cumulativeMonthlyChurn": "0.96%",
        "premium3dMonthlyChurn": "0.63%",
        "stockMonthlyChurn": "3.91%",
        "incrementalMonthlyChurn": "1.03%",
        "tenYearChurnScaleYoY": 47.5
      },
      "kpiValuePct": {
        "globalRetention": 0.987,
        "contractRate": 0.862,
        "otherNetMainCardRate": 0.059000000000000004,
        "threePlanPenetration": 0.115,
        "cumulativeMonthlyChurn": 0.0096,
        "premium3dMonthlyChurn": 0.0063,
        "stockMonthlyChurn": 0.0391,
        "incrementalMonthlyChurn": 0.0103
      },
      "qualityFlags": []
    },
    {
      "name": "山东",
      "sourceRow": 13,
      "top1Intent": true,
      "dataAccess": "1、OB数据融合\n2、O域数据：DPI/NWDAF/位置、SA",
      "dataGovernance": null,
      "modelCapability": "小模型为主",
      "challenge": "价值流量经营，精准营销使能体验经营",
      "networkExperienceRights": null,
      "wave": 3,
      "platform": {
        "bigData": "亚信",
        "iop": "华为",
        "crm": "华为",
        "boss": "华为",
        "seq": "中兴",
        "nwdaf": "华为",
        "ado": "微品+华为"
      },
      "landscape": "部分格局",
      "kpi": {
        "globalRetention": "98.2%",
        "contractRate": "68.9%",
        "otherNetMainCardRate": "6.3%",
        "threePlanPenetration": "13.4%",
        "cumulativeMonthlyChurn": "1.08%",
        "premium3dMonthlyChurn": "0.64%",
        "stockMonthlyChurn": "4.84%",
        "incrementalMonthlyChurn": "3.44%",
        "tenYearChurnScaleYoY": 16
      },
      "kpiValuePct": {
        "globalRetention": 0.982,
        "contractRate": 0.6890000000000001,
        "otherNetMainCardRate": 0.063,
        "threePlanPenetration": 0.134,
        "cumulativeMonthlyChurn": 0.0108,
        "premium3dMonthlyChurn": 0.0064,
        "stockMonthlyChurn": 0.0484,
        "incrementalMonthlyChurn": 0.0344
      },
      "qualityFlags": []
    },
    {
      "name": "湖北",
      "sourceRow": 14,
      "top1Intent": true,
      "dataAccess": null,
      "dataGovernance": null,
      "modelCapability": "小模型为主",
      "challenge": "价值流量经营，网络质量提升",
      "networkExperienceRights": null,
      "wave": 3,
      "platform": {
        "bigData": "亚信",
        "iop": "思特奇",
        "crm": "华为",
        "boss": "华为",
        "seq": "中兴",
        "nwdaf": "华为",
        "ado": "亚信+思特奇"
      },
      "landscape": "友商格局",
      "kpi": {
        "globalRetention": "99.5%",
        "contractRate": "71.0%",
        "otherNetMainCardRate": "5.5%",
        "threePlanPenetration": "11.5%",
        "cumulativeMonthlyChurn": "1.13%",
        "premium3dMonthlyChurn": "0.6%",
        "stockMonthlyChurn": "3.93%",
        "incrementalMonthlyChurn": "2.54%",
        "tenYearChurnScaleYoY": 11.4
      },
      "kpiValuePct": {
        "globalRetention": 0.995,
        "contractRate": 0.71,
        "otherNetMainCardRate": 0.055,
        "threePlanPenetration": 0.115,
        "cumulativeMonthlyChurn": 0.0113,
        "premium3dMonthlyChurn": 0.006,
        "stockMonthlyChurn": 0.0393,
        "incrementalMonthlyChurn": 0.0254
      },
      "qualityFlags": []
    },
    {
      "name": "福建",
      "sourceRow": 15,
      "top1Intent": true,
      "dataAccess": null,
      "dataGovernance": null,
      "modelCapability": "小模型为主",
      "challenge": "数据底座建设，存量精细化运营",
      "networkExperienceRights": "场馆包，5G-A流量包，直播包，商旅包，叠加包销售较差",
      "wave": 3,
      "platform": {
        "bigData": "新大陆",
        "iop": "新大陆",
        "crm": "新大陆",
        "boss": "新大陆",
        "seq": "中兴",
        "nwdaf": "中兴",
        "ado": "新大陆"
      },
      "landscape": "友商格局",
      "kpi": {
        "globalRetention": "98.7%",
        "contractRate": "104.0%",
        "otherNetMainCardRate": "4.9%",
        "threePlanPenetration": "10.1%",
        "cumulativeMonthlyChurn": "0.95%",
        "premium3dMonthlyChurn": "0.6%",
        "stockMonthlyChurn": "3.25%",
        "incrementalMonthlyChurn": "3.55%",
        "tenYearChurnScaleYoY": 25.2
      },
      "kpiValuePct": {
        "globalRetention": 0.987,
        "contractRate": 1.04,
        "otherNetMainCardRate": 0.049,
        "threePlanPenetration": 0.10099999999999999,
        "cumulativeMonthlyChurn": 0.0095,
        "premium3dMonthlyChurn": 0.006,
        "stockMonthlyChurn": 0.0325,
        "incrementalMonthlyChurn": 0.0355
      },
      "qualityFlags": [
        "XXXX合约率待复核：104.0%"
      ]
    },
    {
      "name": "广东",
      "sourceRow": 16,
      "top1Intent": false,
      "dataAccess": "1、100+ OBS数据融合\n2、O域数据：DPI/NWDAF、SA",
      "dataGovernance": null,
      "modelCapability": "小模型为主",
      "challenge": "地铁/校园包上量使能体验经营",
      "networkExperienceRights": "基于智能板做过高铁包，场馆包，校园包，地铁包",
      "wave": null,
      "platform": {
        "bigData": "亚信",
        "iop": "华为",
        "crm": "华为",
        "boss": "华为",
        "seq": "华为",
        "nwdaf": "华为",
        "ado": "华为+阿里"
      },
      "landscape": "部分格局",
      "kpi": {
        "globalRetention": "97.3%",
        "contractRate": "80.0%",
        "otherNetMainCardRate": "7.8%",
        "threePlanPenetration": "10.2%",
        "cumulativeMonthlyChurn": "1.82%",
        "premium3dMonthlyChurn": "1%",
        "stockMonthlyChurn": "5.01%",
        "incrementalMonthlyChurn": "2.3%",
        "tenYearChurnScaleYoY": 31.7
      },
      "kpiValuePct": {
        "globalRetention": 0.973,
        "contractRate": 0.8,
        "otherNetMainCardRate": 0.078,
        "threePlanPenetration": 0.102,
        "cumulativeMonthlyChurn": 0.0182,
        "premium3dMonthlyChurn": 0.01,
        "stockMonthlyChurn": 0.0501,
        "incrementalMonthlyChurn": 0.023
      },
      "qualityFlags": []
    },
    {
      "name": "江西",
      "sourceRow": 17,
      "top1Intent": false,
      "dataAccess": "1、OB数据融合\n2、O域数据：DPI/位置",
      "dataGovernance": null,
      "modelCapability": "小模型为主",
      "challenge": null,
      "networkExperienceRights": "融入5G-A权益，未单独发包（集团严控套餐包数量）",
      "wave": null,
      "platform": {
        "bigData": "华为",
        "iop": "亚信",
        "crm": "亚信",
        "boss": "亚信",
        "seq": "华为",
        "nwdaf": "中兴",
        "ado": "华为+炎黄"
      },
      "landscape": "部分格局",
      "kpi": {
        "globalRetention": "99.1%",
        "contractRate": "60.0%",
        "otherNetMainCardRate": "4.0%",
        "threePlanPenetration": "16.7%",
        "cumulativeMonthlyChurn": "1.09%",
        "premium3dMonthlyChurn": "0.6%",
        "stockMonthlyChurn": "3.24%",
        "incrementalMonthlyChurn": "2.02%",
        "tenYearChurnScaleYoY": 12.2
      },
      "kpiValuePct": {
        "globalRetention": 0.991,
        "contractRate": 0.6,
        "otherNetMainCardRate": 0.04,
        "threePlanPenetration": 0.16699999999999998,
        "cumulativeMonthlyChurn": 0.0109,
        "premium3dMonthlyChurn": 0.006,
        "stockMonthlyChurn": 0.032400000000000005,
        "incrementalMonthlyChurn": 0.0202
      },
      "qualityFlags": []
    },
    {
      "name": "宁夏",
      "sourceRow": 18,
      "top1Intent": false,
      "dataAccess": null,
      "dataGovernance": null,
      "modelCapability": "小模型为主",
      "challenge": null,
      "networkExperienceRights": null,
      "wave": null,
      "platform": {
        "bigData": "新大陆",
        "iop": "新大陆",
        "crm": "华为",
        "boss": "华为",
        "seq": "华为",
        "nwdaf": "中兴",
        "ado": "非度+国信"
      },
      "landscape": "友商格局",
      "kpi": {
        "globalRetention": "97.0%",
        "contractRate": "70.7%",
        "otherNetMainCardRate": "7.2%",
        "threePlanPenetration": "11.0%",
        "cumulativeMonthlyChurn": "1.34%",
        "premium3dMonthlyChurn": "0.74%",
        "stockMonthlyChurn": "4.86%",
        "incrementalMonthlyChurn": "3.08%",
        "tenYearChurnScaleYoY": 2
      },
      "kpiValuePct": {
        "globalRetention": 0.97,
        "contractRate": 0.7070000000000001,
        "otherNetMainCardRate": 0.07200000000000001,
        "threePlanPenetration": 0.11,
        "cumulativeMonthlyChurn": 0.0134,
        "premium3dMonthlyChurn": 0.0074,
        "stockMonthlyChurn": 0.048600000000000004,
        "incrementalMonthlyChurn": 0.0308
      },
      "qualityFlags": []
    },
    {
      "name": "北京",
      "sourceRow": 19,
      "top1Intent": false,
      "dataAccess": null,
      "dataGovernance": null,
      "modelCapability": "小模型为主",
      "challenge": null,
      "networkExperienceRights": null,
      "wave": null,
      "platform": {
        "bigData": "亚信",
        "iop": "亚信",
        "crm": "亚信",
        "boss": "亚信",
        "seq": "华为",
        "nwdaf": "华为",
        "ado": "亚信"
      },
      "landscape": "友商格局",
      "kpi": {
        "globalRetention": "98.1%",
        "contractRate": "84.0%",
        "otherNetMainCardRate": "7.4%",
        "threePlanPenetration": "21.2%",
        "cumulativeMonthlyChurn": "1.07%",
        "premium3dMonthlyChurn": "0.78%",
        "stockMonthlyChurn": "2.96%",
        "incrementalMonthlyChurn": "2.78%",
        "tenYearChurnScaleYoY": 6.2
      },
      "kpiValuePct": {
        "globalRetention": 0.981,
        "contractRate": 0.84,
        "otherNetMainCardRate": 0.07400000000000001,
        "threePlanPenetration": 0.212,
        "cumulativeMonthlyChurn": 0.010700000000000001,
        "premium3dMonthlyChurn": 0.0078000000000000005,
        "stockMonthlyChurn": 0.0296,
        "incrementalMonthlyChurn": 0.0278
      },
      "qualityFlags": []
    },
    {
      "name": "上海",
      "sourceRow": 20,
      "top1Intent": false,
      "dataAccess": "1、市场部运营取自B域数据，O域数据应用占比非常低（出于安全管理因素）",
      "dataGovernance": null,
      "modelCapability": "小模型为主",
      "challenge": null,
      "networkExperienceRights": "地铁包（以前），场馆包，申花球迷包，5G-A套餐。叠加包销售效果一般",
      "wave": null,
      "platform": {
        "bigData": "亚信",
        "iop": "亚信",
        "crm": "亚信",
        "boss": "亚信",
        "seq": "诺基亚",
        "nwdaf": "华为",
        "ado": "亚信+新大陆"
      },
      "landscape": "友商格局",
      "kpi": {
        "globalRetention": "96.0%",
        "contractRate": "82.5%",
        "otherNetMainCardRate": "7.0%",
        "threePlanPenetration": "14.8%",
        "cumulativeMonthlyChurn": "1.32%",
        "premium3dMonthlyChurn": "0.52%",
        "stockMonthlyChurn": "5.22%",
        "incrementalMonthlyChurn": "2.5%",
        "tenYearChurnScaleYoY": -14.3
      },
      "kpiValuePct": {
        "globalRetention": 0.96,
        "contractRate": 0.825,
        "otherNetMainCardRate": 0.07,
        "threePlanPenetration": 0.14800000000000002,
        "cumulativeMonthlyChurn": 0.0132,
        "premium3dMonthlyChurn": 0.0052,
        "stockMonthlyChurn": 0.052199999999999996,
        "incrementalMonthlyChurn": 0.025
      },
      "qualityFlags": []
    },
    {
      "name": "陕西",
      "sourceRow": 21,
      "top1Intent": false,
      "dataAccess": null,
      "dataGovernance": null,
      "modelCapability": "小模型为主",
      "challenge": null,
      "networkExperienceRights": null,
      "wave": null,
      "platform": {
        "bigData": "亚信",
        "iop": "亚信",
        "crm": "亚信",
        "boss": "亚信",
        "seq": "中兴",
        "nwdaf": "华为",
        "ado": "微品+亚信"
      },
      "landscape": "友商格局",
      "kpi": {
        "globalRetention": "97.8%",
        "contractRate": "87.9%",
        "otherNetMainCardRate": "9.3%",
        "threePlanPenetration": "9.3%",
        "cumulativeMonthlyChurn": "1.2%",
        "premium3dMonthlyChurn": "0.98%",
        "stockMonthlyChurn": "3.01%",
        "incrementalMonthlyChurn": "1.66%",
        "tenYearChurnScaleYoY": 5.7
      },
      "kpiValuePct": {
        "globalRetention": 0.978,
        "contractRate": 0.879,
        "otherNetMainCardRate": 0.09300000000000001,
        "threePlanPenetration": 0.09300000000000001,
        "cumulativeMonthlyChurn": 0.012,
        "premium3dMonthlyChurn": 0.0098,
        "stockMonthlyChurn": 0.0301,
        "incrementalMonthlyChurn": 0.0166
      },
      "qualityFlags": []
    },
    {
      "name": "安徽",
      "sourceRow": 22,
      "top1Intent": false,
      "dataAccess": null,
      "dataGovernance": null,
      "modelCapability": "小模型为主",
      "challenge": null,
      "networkExperienceRights": "仅高铁包，销售不理想",
      "wave": null,
      "platform": {
        "bigData": "亚信",
        "iop": "东信北邮",
        "crm": "思特奇",
        "boss": "思特奇",
        "seq": "华为",
        "nwdaf": "华为",
        "ado": "非度"
      },
      "landscape": "友商格局",
      "kpi": {
        "globalRetention": "98.0%",
        "contractRate": "84.8%",
        "otherNetMainCardRate": "7.6%",
        "threePlanPenetration": "12.3%",
        "cumulativeMonthlyChurn": "1%",
        "premium3dMonthlyChurn": "0.77%",
        "stockMonthlyChurn": "2.71%",
        "incrementalMonthlyChurn": "2.01%",
        "tenYearChurnScaleYoY": 4.6
      },
      "kpiValuePct": {
        "globalRetention": 0.98,
        "contractRate": 0.848,
        "otherNetMainCardRate": 0.076,
        "threePlanPenetration": 0.12300000000000001,
        "cumulativeMonthlyChurn": 0.01,
        "premium3dMonthlyChurn": 0.0077,
        "stockMonthlyChurn": 0.0271,
        "incrementalMonthlyChurn": 0.020099999999999996
      },
      "qualityFlags": []
    },
    {
      "name": "青海",
      "sourceRow": 23,
      "top1Intent": false,
      "dataAccess": null,
      "dataGovernance": null,
      "modelCapability": "小模型为主",
      "challenge": null,
      "networkExperienceRights": null,
      "wave": null,
      "platform": {
        "bigData": "亚信",
        "iop": "亚信",
        "crm": "亚信",
        "boss": "亚信",
        "seq": "中兴",
        "nwdaf": "华为",
        "ado": "微品+亚信"
      },
      "landscape": "友商格局",
      "kpi": {
        "globalRetention": "97.1%",
        "contractRate": "79.8%",
        "otherNetMainCardRate": "6.9%",
        "threePlanPenetration": "16.0%",
        "cumulativeMonthlyChurn": "1.46%",
        "premium3dMonthlyChurn": "0.7%",
        "stockMonthlyChurn": "4.17%",
        "incrementalMonthlyChurn": "4.68%",
        "tenYearChurnScaleYoY": -0.1
      },
      "kpiValuePct": {
        "globalRetention": 0.971,
        "contractRate": 0.7979999999999999,
        "otherNetMainCardRate": 0.069,
        "threePlanPenetration": 0.16,
        "cumulativeMonthlyChurn": 0.0146,
        "premium3dMonthlyChurn": 0.006999999999999999,
        "stockMonthlyChurn": 0.0417,
        "incrementalMonthlyChurn": 0.046799999999999994
      },
      "qualityFlags": []
    },
    {
      "name": "浙江",
      "sourceRow": 24,
      "top1Intent": false,
      "dataAccess": "1、100+ OB数据融合\n2、O域数据：SEQ",
      "dataGovernance": "O域数据治理",
      "modelCapability": "小模型为主",
      "challenge": null,
      "networkExperienceRights": "做过浙BA场馆包，销售量很少；\n咪咕爱看XXG的定向免流；",
      "wave": null,
      "platform": {
        "bigData": "亚信",
        "iop": "亚信",
        "crm": "亚信",
        "boss": "亚信",
        "seq": "华为",
        "nwdaf": "华为",
        "ado": "亚信"
      },
      "landscape": "友商格局",
      "kpi": {
        "globalRetention": "98.7%",
        "contractRate": "78.0%",
        "otherNetMainCardRate": "5.0%",
        "threePlanPenetration": "13.8%",
        "cumulativeMonthlyChurn": "1.64%",
        "premium3dMonthlyChurn": "0.97%",
        "stockMonthlyChurn": "7.22%",
        "incrementalMonthlyChurn": "4.53%",
        "tenYearChurnScaleYoY": 20.4
      },
      "kpiValuePct": {
        "globalRetention": 0.987,
        "contractRate": 0.78,
        "otherNetMainCardRate": 0.05,
        "threePlanPenetration": 0.138,
        "cumulativeMonthlyChurn": 0.016399999999999998,
        "premium3dMonthlyChurn": 0.0097,
        "stockMonthlyChurn": 0.0722,
        "incrementalMonthlyChurn": 0.0453
      },
      "qualityFlags": []
    },
    {
      "name": "海南",
      "sourceRow": 25,
      "top1Intent": false,
      "dataAccess": null,
      "dataGovernance": null,
      "modelCapability": "小模型为主",
      "challenge": null,
      "networkExperienceRights": null,
      "wave": null,
      "platform": {
        "bigData": "新大陆",
        "iop": "新大陆",
        "crm": "亚信",
        "boss": "亚信",
        "seq": "诺基亚",
        "nwdaf": "华为",
        "ado": "华为+新大陆"
      },
      "landscape": "友商格局",
      "kpi": {
        "globalRetention": "102.0%",
        "contractRate": "49.0%",
        "otherNetMainCardRate": "7.1%",
        "threePlanPenetration": "18.0%",
        "cumulativeMonthlyChurn": "1.15%",
        "premium3dMonthlyChurn": "0.66%",
        "stockMonthlyChurn": "3%",
        "incrementalMonthlyChurn": "1.81%",
        "tenYearChurnScaleYoY": 8.1
      },
      "kpiValuePct": {
        "globalRetention": 1.02,
        "contractRate": 0.49,
        "otherNetMainCardRate": 0.071,
        "threePlanPenetration": 0.18,
        "cumulativeMonthlyChurn": 0.0115,
        "premium3dMonthlyChurn": 0.0066,
        "stockMonthlyChurn": 0.03,
        "incrementalMonthlyChurn": 0.0181
      },
      "qualityFlags": [
        "拍照全球通保有率待复核：102.0%"
      ]
    },
    {
      "name": "江苏",
      "sourceRow": 26,
      "top1Intent": false,
      "dataAccess": null,
      "dataGovernance": null,
      "modelCapability": "小模型为主",
      "challenge": null,
      "networkExperienceRights": "基于智能板推过场馆包、直播包，高端用户已默开5G-A权益",
      "wave": null,
      "platform": {
        "bigData": "新大陆",
        "iop": "新大陆",
        "crm": "华为",
        "boss": "新大陆",
        "seq": "华为",
        "nwdaf": "华为",
        "ado": "新大陆"
      },
      "landscape": "友商格局",
      "kpi": {
        "globalRetention": "98.7%",
        "contractRate": "42.6%",
        "otherNetMainCardRate": "6.5%",
        "threePlanPenetration": "12.4%",
        "cumulativeMonthlyChurn": "1.4%",
        "premium3dMonthlyChurn": "0.76%",
        "stockMonthlyChurn": "5.28%",
        "incrementalMonthlyChurn": "4.19%",
        "tenYearChurnScaleYoY": 6.7
      },
      "kpiValuePct": {
        "globalRetention": 0.987,
        "contractRate": 0.426,
        "otherNetMainCardRate": 0.065,
        "threePlanPenetration": 0.124,
        "cumulativeMonthlyChurn": 0.013999999999999999,
        "premium3dMonthlyChurn": 0.0076,
        "stockMonthlyChurn": 0.0528,
        "incrementalMonthlyChurn": 0.04190000000000001
      },
      "qualityFlags": []
    },
    {
      "name": "吉林",
      "sourceRow": 27,
      "top1Intent": false,
      "dataAccess": null,
      "dataGovernance": null,
      "modelCapability": "小模型为主",
      "challenge": null,
      "networkExperienceRights": null,
      "wave": null,
      "platform": {
        "bigData": "东方国信",
        "iop": "东方国信",
        "crm": "思特奇",
        "boss": "思特奇",
        "seq": "华为",
        "nwdaf": "华为",
        "ado": "微品+华为"
      },
      "landscape": "友商格局",
      "kpi": {
        "globalRetention": "98.1%",
        "contractRate": "79.0%",
        "otherNetMainCardRate": "7.7%",
        "threePlanPenetration": "17.9%",
        "cumulativeMonthlyChurn": "1.2%",
        "premium3dMonthlyChurn": "0.81%",
        "stockMonthlyChurn": "3.5%",
        "incrementalMonthlyChurn": "2.01%",
        "tenYearChurnScaleYoY": 52.5
      },
      "kpiValuePct": {
        "globalRetention": 0.981,
        "contractRate": 0.79,
        "otherNetMainCardRate": 0.077,
        "threePlanPenetration": 0.179,
        "cumulativeMonthlyChurn": 0.012,
        "premium3dMonthlyChurn": 0.008100000000000001,
        "stockMonthlyChurn": 0.035,
        "incrementalMonthlyChurn": 0.020099999999999996
      },
      "qualityFlags": []
    },
    {
      "name": "山西",
      "sourceRow": 28,
      "top1Intent": false,
      "dataAccess": null,
      "dataGovernance": null,
      "modelCapability": "小模型为主",
      "challenge": null,
      "networkExperienceRights": null,
      "wave": null,
      "platform": {
        "bigData": "斯特奇",
        "iop": "思特奇",
        "crm": "思特奇",
        "boss": "思特奇",
        "seq": "华为",
        "nwdaf": "华为",
        "ado": "思特奇"
      },
      "landscape": "友商格局",
      "kpi": {
        "globalRetention": "99.0%",
        "contractRate": "66.9%",
        "otherNetMainCardRate": "3.4%",
        "threePlanPenetration": "8.3%",
        "cumulativeMonthlyChurn": "1.25%",
        "premium3dMonthlyChurn": "0.67%",
        "stockMonthlyChurn": "3.02%",
        "incrementalMonthlyChurn": "3.51%",
        "tenYearChurnScaleYoY": -3.1
      },
      "kpiValuePct": {
        "globalRetention": 0.99,
        "contractRate": 0.669,
        "otherNetMainCardRate": 0.034,
        "threePlanPenetration": 0.083,
        "cumulativeMonthlyChurn": 0.0125,
        "premium3dMonthlyChurn": 0.0067,
        "stockMonthlyChurn": 0.0302,
        "incrementalMonthlyChurn": 0.0351
      },
      "qualityFlags": []
    },
    {
      "name": "新疆",
      "sourceRow": 29,
      "top1Intent": false,
      "dataAccess": null,
      "dataGovernance": null,
      "modelCapability": "小模型为主",
      "challenge": null,
      "networkExperienceRights": null,
      "wave": null,
      "platform": {
        "bigData": "新大陆",
        "iop": "亚信",
        "crm": "亚信",
        "boss": "华为",
        "seq": "华为",
        "nwdaf": "中兴",
        "ado": "亚信"
      },
      "landscape": "友商格局",
      "kpi": {
        "globalRetention": null,
        "contractRate": null,
        "otherNetMainCardRate": null,
        "threePlanPenetration": "6.2%",
        "cumulativeMonthlyChurn": "2.5%",
        "premium3dMonthlyChurn": "1%",
        "stockMonthlyChurn": "5.22%",
        "incrementalMonthlyChurn": "2.45%",
        "tenYearChurnScaleYoY": -0.6
      },
      "kpiValuePct": {
        "globalRetention": null,
        "contractRate": null,
        "otherNetMainCardRate": null,
        "threePlanPenetration": 0.062,
        "cumulativeMonthlyChurn": 0.025,
        "premium3dMonthlyChurn": 0.01,
        "stockMonthlyChurn": 0.052199999999999996,
        "incrementalMonthlyChurn": 0.0245
      },
      "qualityFlags": [
        "拍照全球通保有率缺失",
        "XXXX合约率缺失",
        "拍照全球通保有率跨表冲突：数据收集表为 0，省份数据表为空"
      ]
    },
    {
      "name": "辽宁",
      "sourceRow": 30,
      "top1Intent": false,
      "dataAccess": null,
      "dataGovernance": null,
      "modelCapability": "小模型为主",
      "challenge": null,
      "networkExperienceRights": null,
      "wave": null,
      "platform": {
        "bigData": "亚信",
        "iop": "亚信",
        "crm": "亚信",
        "boss": "亚信",
        "seq": "中兴",
        "nwdaf": "华为",
        "ado": "亚信"
      },
      "landscape": "友商格局",
      "kpi": {
        "globalRetention": "96.8%",
        "contractRate": "72.7%",
        "otherNetMainCardRate": "7.3%",
        "threePlanPenetration": "10.4%",
        "cumulativeMonthlyChurn": "0.88%",
        "premium3dMonthlyChurn": "0.64%",
        "stockMonthlyChurn": "3%",
        "incrementalMonthlyChurn": "2.76%",
        "tenYearChurnScaleYoY": -7
      },
      "kpiValuePct": {
        "globalRetention": 0.968,
        "contractRate": 0.727,
        "otherNetMainCardRate": 0.073,
        "threePlanPenetration": 0.10400000000000001,
        "cumulativeMonthlyChurn": 0.0088,
        "premium3dMonthlyChurn": 0.0064,
        "stockMonthlyChurn": 0.03,
        "incrementalMonthlyChurn": 0.0276
      },
      "qualityFlags": []
    },
    {
      "name": "内蒙古",
      "sourceRow": 31,
      "top1Intent": false,
      "dataAccess": null,
      "dataGovernance": null,
      "modelCapability": "小模型为主",
      "challenge": null,
      "networkExperienceRights": null,
      "wave": null,
      "platform": {
        "bigData": "苏研",
        "iop": "东方国信",
        "crm": "亚信",
        "boss": "亚信",
        "seq": "华为",
        "nwdaf": "华为",
        "ado": "华为+微品"
      },
      "landscape": "友商格局",
      "kpi": {
        "globalRetention": "99.0%",
        "contractRate": "92.5%",
        "otherNetMainCardRate": "8.0%",
        "threePlanPenetration": "7.8%",
        "cumulativeMonthlyChurn": "0.57%",
        "premium3dMonthlyChurn": "0.53%",
        "stockMonthlyChurn": "2.4%",
        "incrementalMonthlyChurn": "3.8%",
        "tenYearChurnScaleYoY": -17.2
      },
      "kpiValuePct": {
        "globalRetention": 0.99,
        "contractRate": 0.925,
        "otherNetMainCardRate": 0.08,
        "threePlanPenetration": 0.078,
        "cumulativeMonthlyChurn": 0.005699999999999999,
        "premium3dMonthlyChurn": 0.0053,
        "stockMonthlyChurn": 0.024,
        "incrementalMonthlyChurn": 0.038
      },
      "qualityFlags": []
    },
    {
      "name": "云南",
      "sourceRow": 32,
      "top1Intent": false,
      "dataAccess": null,
      "dataGovernance": null,
      "modelCapability": "小模型为主",
      "challenge": null,
      "networkExperienceRights": null,
      "wave": null,
      "platform": {
        "bigData": "亚信",
        "iop": "亚信",
        "crm": "亚信",
        "boss": "亚信",
        "seq": "华为",
        "nwdaf": "华为",
        "ado": "亚信+欣网"
      },
      "landscape": "友商格局",
      "kpi": {
        "globalRetention": "98.3%",
        "contractRate": "80.2%",
        "otherNetMainCardRate": "3.3%",
        "threePlanPenetration": "11.2%",
        "cumulativeMonthlyChurn": "1.29%",
        "premium3dMonthlyChurn": "0.8%",
        "stockMonthlyChurn": "4.3%",
        "incrementalMonthlyChurn": "5.85%",
        "tenYearChurnScaleYoY": 16.6
      },
      "kpiValuePct": {
        "globalRetention": 0.983,
        "contractRate": 0.802,
        "otherNetMainCardRate": 0.033,
        "threePlanPenetration": 0.11199999999999999,
        "cumulativeMonthlyChurn": 0.0129,
        "premium3dMonthlyChurn": 0.008,
        "stockMonthlyChurn": 0.043,
        "incrementalMonthlyChurn": 0.058499999999999996
      },
      "qualityFlags": []
    },
    {
      "name": "西藏",
      "sourceRow": 33,
      "top1Intent": false,
      "dataAccess": null,
      "dataGovernance": null,
      "modelCapability": "小模型为主",
      "challenge": null,
      "networkExperienceRights": null,
      "wave": null,
      "platform": {
        "bigData": "亚信",
        "iop": "亚信",
        "crm": "亚信",
        "boss": "亚信",
        "seq": "中兴",
        "nwdaf": "华为",
        "ado": "亚信"
      },
      "landscape": "友商格局",
      "kpi": {
        "globalRetention": "98.8%",
        "contractRate": "67.0%",
        "otherNetMainCardRate": "5.6%",
        "threePlanPenetration": "5.0%",
        "cumulativeMonthlyChurn": "2.2%",
        "premium3dMonthlyChurn": "1%",
        "stockMonthlyChurn": "5.22%",
        "incrementalMonthlyChurn": "2.45%",
        "tenYearChurnScaleYoY": -19.7
      },
      "kpiValuePct": {
        "globalRetention": 0.988,
        "contractRate": 0.67,
        "otherNetMainCardRate": 0.055999999999999994,
        "threePlanPenetration": 0.05,
        "cumulativeMonthlyChurn": 0.022000000000000002,
        "premium3dMonthlyChurn": 0.01,
        "stockMonthlyChurn": 0.052199999999999996,
        "incrementalMonthlyChurn": 0.0245
      },
      "qualityFlags": []
    }
  ]
};
